// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmp2wN_ARKecJGKdteFj9Tr6JTrJKPHSI',
    appId: '1:424854184365:android:e310e76980745272298124',
    messagingSenderId: '424854184365',
    projectId: 'e-learning-60299',
    storageBucket: 'e-learning-60299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvU_zehLAeWVq0oMtxfJt-X6ZwuaFWaYU',
    appId: '1:424854184365:ios:cb6567942c0ca215298124',
    messagingSenderId: '424854184365',
    projectId: 'e-learning-60299',
    storageBucket: 'e-learning-60299.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5x10yUdC3rV6YifjAIEjJqu3wPWe_N_c',
    appId: '1:424854184365:web:c7b45172b9301a9c298124',
    messagingSenderId: '424854184365',
    projectId: 'e-learning-60299',
    authDomain: 'e-learning-60299.firebaseapp.com',
    storageBucket: 'e-learning-60299.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvU_zehLAeWVq0oMtxfJt-X6ZwuaFWaYU',
    appId: '1:424854184365:ios:cb6567942c0ca215298124',
    messagingSenderId: '424854184365',
    projectId: 'e-learning-60299',
    storageBucket: 'e-learning-60299.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5x10yUdC3rV6YifjAIEjJqu3wPWe_N_c',
    appId: '1:424854184365:web:9e1ca6eaced4c7b2298124',
    messagingSenderId: '424854184365',
    projectId: 'e-learning-60299',
    authDomain: 'e-learning-60299.firebaseapp.com',
    storageBucket: 'e-learning-60299.firebasestorage.app',
  );

}